#things that need to be sorted still:
#cleanup command?
#threading
#settings optimizer
---
- general_settings:
        algorithm_name: "bwa"
        algorithm_version: "1.0.0"
        command: "sleep 10s"
- timed_command:
        repeats: 3
        threads: 32
        output: "time_out"
- thread_scaling:
        repeats: 3
        threads: 1,2,4,6,8,10,12,14,16,18,20,24,28,32,64
        output: "thread_out"
- memory_footprint:
        repeats: 3
        output: "mem_out"

